; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:attiny85]
platform = atmelavr
board = attiny85
framework = arduino
board_build.f_cpu = 16000000L
build_flags = 
	-DF_CPU=16000000L
	-DARDUINO_AVR_ATTINYX5
	-DCLOCK_SOURCE=8
lib_deps = 
	OneWire @ 2.3.5
	adafruit/Adafruit NeoPixel
	https://github.com/ChrisMicro/_8Bit-Mixtape-NEO-Lib.git
extra_scripts = 
	scripts/hex2wav_post.py
hex2wav_cmd = tools/hex2wav/linux/hex2wav64_bin {hex} {wav}
hex2wav_auto_play = yes
hex2wav_player_cmd = aplay -q {wav}
upload_protocol = custom
upload_command = tools/hex2wav/linux/hex2wav64_bin $SOURCE .pio/build/${PIOENV}/${PROGNAME}.wav && aplay -q .pio/build/${PIOENV}/${PROGNAME}.wav

[platformio]
description = Attiny85 project including functional audio upload like the 8Bit Mixtape
